photostore/store/views.py
from photostore import filetools, db
from photostore.modules.editorjs import renderBlock
from photostore.permissions import admin_perm
from photostore.store.whoosh_schemas import PhotoIndexSchema
from photostore.store.forms import PhotoDetailsForm, SearchPhotosForm
from photostore.store.models import Photo, PhotoCoverage, PhotoPaginaBusqueda
from photostore.store.utiles import StorageController
from photostore.store.permissions import DownloadCoveragePermission
from photostore.store.permissions import EditPhotoPermission
from photostore.store.permissions import DownloadPhotoPermission
from photostore.store.permissions import EDIT_PHOTO, DOWNLOAD_PHOTO
from whoosh.filedb.filestore import FileStorage
from whoosh.qparser import QueryParser
from whoosh import sorting
from flask_login import login_required, current_user
from flask_breadcrumbs import register_breadcrumb, default_breadcrumb_root
from flask_menu import register_menu, current_menu
from flask import Blueprint, current_app, render_template, abort
from flask import request, json, send_file, request, url_for
from flask import stream_with_context
from flask import Response
from pathlib import Path
from werkzeug.utils import redirect, secure_filename
import os
import tempfile
import datetime


bp = Blueprint(
    'photos', __name__, template_folder='templates')
default_breadcrumb_root(bp, '.index')


def can_edit_cobertura(cob: PhotoCoverage):
    return (cob.author_id == current_user.id) or admin_perm.can()


@bp.context_processor
def bp_context():
    def can_download(id):
        """Can download original image"""
        return DownloadPhotoPermission(id=id).can()

    def can_download_coverage(id):
        return DownloadCoveragePermission(id).can()

    return {
        'can_download_photo': can_download,
        'can_download_coverage': can_download_coverage
    }


@bp.before_app_first_request
def setupMenus():
    navbar = current_menu.submenu("navbar.photostore")
    navbar._external_url = "#!"
    navbar._endpoint = None
    navbar._text = "NAVBAR"

    # mis actions
    actions = current_menu.submenu("actions.photostore")
    actions._text = "Fotos"
    actions._endpoint = None
    actions._external_url = "#!"


@bp.route('/photo/preview/<id>')
def photo_thumbnail(id):
    p = Photo.query.get_or_404(id)
    if Path(p.thumbnail).is_file() is False:
        # this is slow but ensure the thumbnail is there in the next load
        StorageController.getInstance().generateThumbnail(p)
        abort(404)
    return send_file(p.thumbnail)


@bp.route('/photo/download/archive/<id>')
@login_required
def photo_download(id):
    """Descargar el zip con la foto y la información de la foto"""
    web_ready = True if request.args.get('web') else False
    if DownloadPhotoPermission(id=id).can() is False and web_ready is False:
        abort(403)
    p = Photo.query.get_or_404(id)
    file_name = StorageController.getInstance().makePhotoZip(
        p, web_ready=web_ready)
    file_handle = open(file_name, 'rb')

    def stream_and_remove():
        yield from file_handle
        file_handle.close()
        os.remove(file_name)

    return Response(
        stream_with_context(stream_and_remove()),
        headers={
            'Content-Type': 'application/zip',
            'Content-Disposition': 'attachment; filename="{}"'.format(
                Path(file_name).name)
        }
    )


def view_photo_download_page_dlc(*args, **kwargs):
    id = request.view_args['id']
    return [
        {
            'text': 'Exportar',
            'url': url_for('.photo_download_page', id=id)
        }
    ]


@bp.route('/photo/download/<id>')
@register_breadcrumb(
    bp, '.index.photo_download_page', '',
    dynamic_list_constructor=view_photo_download_page_dlc)
@login_required
def photo_download_page(id):
    """Present page with export options"""
    photo = Photo.query.get_or_404(id)
    return render_template(
        'store/photo_download_page.html',
        foto=photo)


def view_photo_details_dlc(*args, **kwargs):
    id = request.view_args['id']
    return [
        {
            'text': 'Detalles',
            'url': url_for('.photo_details', id=id)
        }
    ]


@bp.route('/photo/details/<id>')
@register_breadcrumb(
    bp, '.index.photo_details.id', 'Detalles',
    dynamic_list_constructor=view_photo_details_dlc)
@login_required
def photo_details(id):
    p = Photo.query.get_or_404(id)
    can_edit = EditPhotoPermission(p.md5)
    return render_template(
        'store/photo_details.html', foto=p, can_edit=can_edit)


@bp.route('/photo/edit/<id>', methods=['GET', 'POST'])
@register_breadcrumb(bp, '.index.photo_edit.id', 'Editar datos de la foto')
def photo_edit(id):
    p = Photo.query.get_or_404(id)
    can_edit = EditPhotoPermission(p.md5)
    if can_edit is False:
        abort(403)

    form = PhotoDetailsForm()
    if form.validate_on_submit():
        p.headline = form.headline.data
        p.credit_line = form.credit_line.data
        p.excerpt = form.excerpt.data
        tags = list(filter(None, json.loads(form.tags.data)))
        p.keywords = [t.lower() for t in tags]
        db.session.add(p)
        db.session.commit()
        # reindexar la foto para que consten los cambios
        StorageController.getInstance().indexPhoto(p)
        return redirect(url_for('.photo_details', id=p.md5))

    return render_template(
        'store/photo_edit.html', foto=p, form=form)


@bp.route('/')
@register_breadcrumb(bp, '.index', 'Fotos')
@register_menu(bp, 'navbar.photostore.index', 'Fotos')
@register_menu(bp, 'actions.photostore.index', 'Galerias')
@login_required
def index():
    page = request.args.get('page', 1, type=int)
    form = SearchPhotosForm()
    coberturas = PhotoCoverage.query.order_by(
        PhotoCoverage.archive_on.desc()).paginate(page, per_page=4)

    return render_template(
        'store/index.html', coberturas=coberturas,
        form=form, can_edit=can_edit_cobertura)


def verCobertura_dlc(*args, **kwargs):
    id = request.view_args['id']
    cob = PhotoCoverage.query.get_or_404(id)
    return [
        {
            'text': cob.headline,
            'url': url_for('.verCobertura', id=cob.id)
        }
    ]


@bp.route('/ver/cobertura/<id>')
@register_breadcrumb(
    bp, '.index.verCobertura', '',
    dynamic_list_constructor=verCobertura_dlc)
def verCobertura(id):
    cobertura = PhotoCoverage.query.get_or_404(id)
    form = SearchPhotosForm()
    return render_template(
        "store/ver_cobertura.html",
        cobertura=cobertura,
        form=form,
        can_edit=can_edit_cobertura)


def view_editarCobertura_dlc(*args, **kwargs):
    id = request.view_args['id']
    cob = PhotoCoverage.query.get_or_404(id)
    return [
        {
            'text': 'Editar Cobertura',
            'url': url_for('.editarCobertura', id=cob.id)
        }
    ]


@bp.route('/editar/cobertura/<id>')
@register_breadcrumb(
    bp, '.index.editarCobertura', '',
    dynamic_list_constructor=view_editarCobertura_dlc)
@login_required
def editarCobertura(id):
    cobertura = PhotoCoverage.query.get_or_404(id)
    if can_edit_cobertura(cobertura) is False:
        abort(403)

    return render_template(
        'store/editar_cobertura.html', cobertura=cobertura)


@bp.route('/myphotos')
@register_breadcrumb(bp, '.index.mis_fotos', 'Mis fotos')
@register_menu(bp, 'actions.photostore.mis_fotos', 'Mis fotos')
@login_required
def mis_fotos():
    """Las fotos de este usuario"""
    page = request.args.get('page', 1, type=int)
    form = SearchPhotosForm()
    photos = Photo.query.filter_by(
        upload_by=current_user.id
    ).order_by(
        Photo.archive_on.desc()).paginate(page, per_page=12)
    return render_template(
        'store/mis_fotos.html', fotos=photos, search_form=form)


@bp.route('/search', methods=['GET', 'POST'])
@register_breadcrumb(bp, '.index.buscar_indice', 'Buscar')
@register_menu(
    bp, 'actions.photostore.buscar_indice', 'Buscar Fotos')
@login_required
def buscar_indice():
    form = SearchPhotosForm()
    userquery = request.args.get('userquery', "")
    try:
        page = int(request.args.get('page', '1'))
        page = page if page > 0 else 1
    except ValueError:
        page = 1

    if form.validate_on_submit():
        userquery = form.userquery.data

    # hacer la busqueda aqui
    base = Path(current_app.config.get('INDEX_BASE_DIR'))
    store = FileStorage(str(base / 'photos'))
    ix = store.open_index()
    qp = QueryParser("excerpt", PhotoIndexSchema())
    keywords_facet = sorting.FieldFacet("keywords", maptype=sorting.Count)
    taken_facet = sorting.DateRangeFacet(
        "taken_on",
        datetime.datetime(2002, 1, 1),
        datetime.datetime.now(),
        datetime.timedelta(days=30),
        maptype=sorting.Count
    )

    with ix.searcher() as s:
        results = PhotoPaginaBusqueda(s.search_page(
            qp.parse(userquery, debug=False), page, pagelen=9,
            groupedby={
                "keywords": keywords_facet,
                "taken_on": taken_facet,
            },
            sortedby="taken_on", reverse=True)
        )

        keywords_grp = dict()
        # extraer las agrupaciones por keywords de los resultados
        for k, v in results.groups(name="keywords").items():
            keywords_grp[k] = {
                "documents": v,
                "text": k,
                "link": url_for(
                    '.buscar_indice',
                    userquery='keywords:"{}" {}'.format(
                        k, userquery))
            }
        # --

        # extraer los rangos de fechas
        taken_grp = dict()
        for k, v in results.groups(name="taken_on").items():
            if k is not None:
                start, end = k  # es una tupla
                taken_grp[k] = {  # range name
                    "documents": v,  # cantidad de documentos
                    "start": start,
                    "end": end,
                    "link": url_for(

photostore/views/admin.py
from photostore.permissions import admin_perm
from flask import Blueprint, render_template
from photostore.store.cruds import VolumeCRUD
from flask_menu import current_menu, register_menu

admin_bp = Blueprint('admin_bp', __name__, url_prefix='/crud')
volume_bp = Blueprint('volume_bp', __name__, url_prefix='/crud/volume')

admin_decore = [admin_perm.require(http_exception=403)]
VolumeCRUD(
    create_decorators=admin_decore,
    index_decorators=admin_decore,
    edit_decorators=admin_decore,
).register(volume_bp)


@volume_bp.before_app_first_request
def setupMenus():
    # sidebar entries
    actions = current_menu.submenu("actions.admin")
    actions._text = "Administración"
    actions._endpoint = None
    actions._external_url = "#!"

@admin_bp.route("/", methods=['GET'])
@admin_perm.require(http_exception=403)
@register_menu(
    admin_bp, "actions.admin.models", "Modelos",
    visible_when=lambda: admin_perm.can())
def admin_view():
    return render_template("admin/admin_view.html")

photostore/templates/volume/create.html
{% extends 'layout.html' %}

{% block page_title %}Admin - Crear volumen{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <form action="" method="post" class="col s12">
            <h2>Crear volumen</h2>
            {{ form.hidden_tag() }}
            <div class="row">
                <div class="col s12 input-field">
                    {{ form.name.label }}
                    {{ form.name }}
                    {% for error in form.name.errors %}
                    <p class="red-text text-darken-3">{{ error }}</p>
                    {% endfor %}
                </div>
            </div>
            <div class="row">
                <div class="col s12 input-field">
                    {{ form.capacity.label }}
                    {{ form.capacity }}
                    {% for error in form.capacity.errors %}
                    <p class="red-text text-darken-3">{{ error }}</p>
                    {% endfor %}
                </div>
            </div>
            <div class="row">
                <div class="col s12 input-field">
                    {{ form.fspath.label }}
                    {{ form.fspath }}
                    {% for error in form.fspath.errors %}
                    <p class="red-text text-darken-3">{{ error }}</p>
                    {% endfor %}
                </div>
            </div>
            <div class="row">
                <div class="input-field col s12">
                    <button class="btn waves-effect waves-light" type="submit" name="action">
                        Crear
                        <i class="material-icons left">send</i>
                    </button>

                    <a href="{{ url_for('volume_bp.index') }}" class="btn waves-effect waves-light">
                        Cancelar
                    </a>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}


{% block breadcrumb %}
<nav class="px-3">
    <div class="nav-wrapper">
        <a href="{{ url_for('photos.index') }}" class="breadcrumb">Inicio</a>
        <a href="{{ url_for('admin_bp.admin_view') }}" class="breadcrumb">Modelos</a>
        <a href="{{ url_for('volume_bp.index') }}" class="breadcrumb">Volumenes</a>
        <a href="{{ url_for('volume_bp.create') }}" class="breadcrumb">Crear</a>
    </div>
</nav>
{% endblock %}

photostore/templates/volume/delete.html
{% extends 'layout.html' %}

{% block page_title %}Admin - Eliminar Volumen{% endblock %}

{% block content %}

<div class="container">
    <div class="row">
        <form action="" method="POST" class="col s12">
            {{ form.hidden_tag() }}
            <h2>Eliminar Volumen</h2>
            <div class="row">
                <div class="col s12 input-field">
                    {{ form.name.label }}
                    {{ form.name }}
                </div>
            </div>
            <div class="row">
                <div class="col s12 input-field">
                    {{ form.fspath.label }}
                    {{ form.fspath }}
                    <span class="helper-text">
                        El directorio no se eliminará
                    </span>
                </div>
            </div>
            <div class="row">
                <div class="input-field col s12">
                    <button class="btn waves-effect waves-light red darken-3" type="submit" name="action">
                        ¿Eliminar el volumen?
                        <i class="material-icons left">delete</i>
                    </button>

                    <a href="{{ url_for('volume_bp.index') }}" class="btn waves-effect waves-light">
                        Cancelar
                    </a>
                </div>
            </div>
        </form>
    </div>
</div>

{% endblock %}


{% block breadcrumb %}
<nav class="px-3">
    <div class="nav-wrapper">
        <a href="{{ url_for('photos.index') }}" class="breadcrumb">Inicio</a>
        <a href="{{ url_for('admin_bp.admin_view') }}" class="breadcrumb">Modelos</a>
        <a href="{{ url_for('volume_bp.index') }}" class="breadcrumb">Volumenes</a>
        <a href="{{ url_for('volume_bp.create') }}" class="breadcrumb">Eliminar</a>
    </div>
</nav>
{% endblock %}

photostore/templates/volume/edit.html
{% extends 'layout.html' %}

{% block page_title %}Admin - Editar Volumen {{ volume.name }}{% endblock %}

{% block content %}

<div class="container">
    <div class="row">
        <form action="" method="POST" class="col s12">
            {{ form.hidden_tag() }}
            <h2>Crear volumen</h2>
            <div class="row">
                <div class="col s12 input-field">
                    {{ form.name.label }}
                    {{ form.name }}
                    {% for error in form.name.errors %}
                    <p class="error-message">{{ error }}</p>
                    {% endfor %}
                </div>
            </div>
            <div class="row">
                <div class="col s12 input-field">
                    {{ form.capacity.label }}
                    {{ form.capacity }}
                    {% for error in form.capacity.errors %}
                    <p class="error-message">{{ error }}</p>
                    {% endfor %}
                </div>
            </div>
            <div class="row">
                <div class="col s12 input-field">
                    {{ form.fspath.label }}
                    {{ form.fspath }}
                    {% for error in form.fspath.errors %}
                    <p class="error-message">{{ error }}</p>
                    {% endfor %}
                </div>
            </div>
            <div class="row">
                <div class="col s12 input-field">
                    <div class="switch">
                        <label>
                            {{ form.is_full }}
                            <span class="lever"></span>
                            {{ form.is_full.label.text }}
                        </label>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="input-field col s12">
                    <button class="btn waves-effect waves-light" type="submit" name="action">
                        Guardar volumen
                        <i class="material-icons left">send</i>
                    </button>

                    <a href="{{ url_for('volume_bp.index') }}" class="btn waves-effect waves-light">
                        Cancelar
                    </a>
                </div>
            </div>
        </form>
    </div>
</div>

{% endblock %}


{% block breadcrumb %}
<nav class="px-3">
    <div class="nav-wrapper">
        <a href="{{ url_for('photos.index') }}" class="breadcrumb">Inicio</a>
        <a href="{{ url_for('admin_bp.admin_view') }}" class="breadcrumb">Modelos</a>
        <a href="{{ url_for('volume_bp.index') }}" class="breadcrumb">Volumenes</a>
        <a href="{{ url_for('volume_bp.create') }}" class="breadcrumb">Editar {{ volume.name }}</a>
    </div>
</nav>
{% endblock %}

photostore/templates/volume/index.html
{% extends 'layout.html' %}

{% block page_title %}Admin - Volumenes{% endblock %}

{% block content %}
    <h3>Volumenes</h3>
    <a href="{{ url_for('volume_bp.create') }}" class="waves-effect waves-light btn">
        <i class="material-icons left">add</i> 
        Crear volumen
    </a>
    <div class="row">
        <table class="col s12">
            <thead>
                <tr>
                    <th>Nombre</th>
                    <th>Capacidad</th>
                    <th>¿Lleno?</th>
                    <th></th>
                </tr>
            </thead>

            <tbody>
                {% for v in volume_list: %}
                <tr>
                    <td>{{ v.name }}</td>
                    <td>
                        {% with per = (100*v.used) // v.capacity %}
                        <div class="modded">
                            <div class="progress">
                                <span>Usado</span>
                                <div class="determinate" style="width: {{ per }}%; animation: grow 2s;">
                                    {{ per }}%
                                </div>
                            </div>
                        </div>
                        {% endwith %}
                    </td>
                    <td>
                        <div class="switch">
                            <label>
                                <input type="checkbox" disabled {{ 'checked' if v.is_full else '' }}>
                                <span class="lever"></span>
                            </label>
                        </div>
                    </td>
                    <td>
                        <a href="{{ url_for('volume_bp.edit', pk=v.id) }}" class="waves-effect waves-light btn-small">
                            <i class="material-icons">edit</i>
                        </a>
                    
                        <a href="{{ url_for('volume_bp.delete', pk=v.id) }}" class="waves-effect waves-light btn-small red darken-3">
                            <i class="material-icons">delete</i>
                        </a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

{% endblock %}


{% block breadcrumb %}
<nav class="px-3">
    <div class="nav-wrapper">
        <a href="{{ url_for('photos.index') }}" class="breadcrumb">Inicio</a>
        <a href="{{ url_for('admin_bp.admin_view') }}" class="breadcrumb">Modelos</a>
        <a href="{{ url_for('volume_bp.index') }}" class="breadcrumb">Volumenes</a>
    </div>
</nav>
{% endblock %}